[
  {
    "py/tuple": [
      {
        "py/object": "objects.Link",
        "src": {
          "py/object": "objects.Exception",
          "type": "org.apache.hadoop.hive.ql.parse.ParseException",
          "method": "org.apache.hadoop.hive.ql.parse.ParseDriver/parse:125",
          "message": "org.apache.hadoop.hive.ql.parse.ParseError@106c37dc"
        },
        "dst": {
          "py/object": "objects.Exception",
          "type": "java.lang.RuntimeException",
          "method": "org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics$CodahaleMetricsScope/open:126",
          "message": "cannot open scope"
        }
      },
      {
        "py/reduce": [
          {
            "py/type": "objects.LinkType"
          },
          {
            "py/tuple": [
              3
            ]
          }
        ]
      }
    ]
  },
  {
    "py/tuple": [
      {
        "py/object": "objects.Link",
        "src": {
          "py/object": "objects.Exception",
          "type": "org.apache.hadoop.hive.ql.parse.ParseException",
          "method": "org.apache.hadoop.hive.ql.parse.ParseDriver/parse:125",
          "message": "org.apache.hadoop.hive.ql.parse.ParseError@106c37dc"
        },
        "dst": {
          "py/object": "objects.Exception",
          "type": "org.apache.hadoop.hive.ql.processors.CommandProcessorException",
          "method": "org.apache.hadoop.hive.ql.DriverUtils/createProcessorException:181",
          "message": "FAILED: ParseException org.apache.hadoop.hive.ql.parse.ParseError@400e60d2"
        }
      },
      {
        "py/id": 4
      }
    ]
  },
  {
    "py/tuple": [
      {
        "py/object": "objects.Link",
        "src": {
          "py/object": "objects.Exception",
          "type": "java.lang.RuntimeException",
          "method": "org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics$CodahaleMetricsScope/open:126",
          "message": "cannot open scope"
        },
        "dst": {
          "py/object": "objects.Exception",
          "type": "org.apache.hadoop.hive.ql.processors.CommandProcessorException",
          "method": "org.apache.hadoop.hive.ql.DriverUtils/createProcessorException:181",
          "message": "FAILED: RuntimeException cannot open scope"
        }
      },
      {
        "py/id": 4
      }
    ]
  },
  {
    "py/tuple": [
      {
        "py/object": "objects.Link",
        "src": {
          "py/object": "objects.Exception",
          "type": "org.apache.hive.service.cli.HiveSQLException",
          "method": "org.apache.hive.service.cli.operation.Operation/toSQLException:372",
          "message": "Error while compiling statement: FAILED: ParseException org.apache.hadoop.hive.ql.parse.ParseError@400e60d2"
        },
        "dst": {
          "py/object": "objects.Exception",
          "type": "org.apache.hive.service.cli.HiveSQLException",
          "method": "org.apache.hive.service.cli.operation.Operation/toSQLException:372",
          "message": "Error while compiling statement: FAILED: RuntimeException cannot open scope"
        }
      },
      {
        "py/id": 4
      }
    ]
  }
]